### ISSUE TITLE
Magentic doesn't marshall response into correct return type when using litellm w/ model ollama_chat/llama3.1

### ISSUE THREAD

**Issue by bhjelmar** [jackmpcollins/magentic#316]
From the example in the docs

```
from dotenv import load_dotenv
load_dotenv()

from typing import Literal

from magentic import prompt, FunctionCall


def search_twitter(query: str, category: Literal["latest", "people"]) -> str:
    """Searches Twitter for a query."""
    print(f"Searching Twitter for {query!r} in category {category!r}")
    return "<twitter results>"


def search_youtube(query: str, channel: str = "all") -> str:
    """Searches YouTube for a query."""
    print(f"Searching YouTube for {query!r} in channel {channel!r}")
    return "<youtube results>"


@prompt(
    "Use the appropriate search function to answer: {question}",
    functions=[search_twitter, search_youtube],
)
def perform_search(question: str) -> FunctionCall[str]: ...


output = perform_search("What is the latest news on LLMs?")
print(output)
# > FunctionCall(<function search_twitter at 0x10c367d00>, 'LLMs', 'latest')
output()
```

Works fine with openai backend but litellm ollama backend returns

```
Traceback (most recent call last):
  File "D:\Developer\PycharmProjects\pythonProject1\main.py", line 28, in <module>
    output = perform_search("What is the latest news on LLMs?")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developer\PycharmProjects\pythonProject1\.venv\Lib\site-packages\magentic\prompt_function.py", line 96, in __call__
    message = self.model.complete(
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\Developer\PycharmProjects\pythonProject1\.venv\Lib\site-packages\magentic\chat_model\litellm_chat_model.py", line 199, in complete
    str_content = validate_str_content(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developer\PycharmProjects\pythonProject1\.venv\Lib\site-packages\magentic\chat_model\base.py", line 61, in validate_str_content
    raise StringNotAllowedError(AssistantMessage(model_output))
magentic.chat_model.base.StringNotAllowedError: A string was returned by the LLM but was not an allowed output type. Consider updating the prompt to encourage the LLM to "use the tool". Model output: '{"name": "search_twitter", "parameters": {"category": "latest", "query": "LLMs"}}'

Process finished with exit code 1

```

**Comment by bhjelmar** [comment]
llama3.1 should support tool calls, https://ollama.com/blog/tool-support
wondering if you might have any guidance on how to make this work?

**Comment by jackmpcollins** [comment]
Hi @bhjelmar ollama's openai-compatible API does not currently support streaming, and magentic uses streaming for all requests (to most easily support `Iterable[X]` and other streamed types). I am tracking this on issue https://github.com/jackmpcollins/magentic/issues/207  You could upvote the relevant ollama issues linked from there to increase their priority.

For the moment you could try using ollama via `LitellmChatModel` as shown in the issue description there, though as described in the issue this is unreliable (maybe LLM-assisted retries can help https://magentic.dev/retrying/).

Closing this to track on https://github.com/jackmpcollins/magentic/issues/207 instead
