### ISSUE TITLE
@prompt_chain error if response model is Generic

### ISSUE THREAD

**Issue by thomasleveil** [jackmpcollins/magentic#49]
Hi, all went well until I introduced generics. Here is a reproduction case 

## Code

```python
from typing import Annotated, Generic, TypeVar

from magentic import prompt_chain
from pydantic import BaseModel, Field


class ApiError(BaseModel):
    code: str
    message: str


T = TypeVar('T')


class ApiResponse(BaseModel, Generic[T]):
    error: ApiError | None = None
    response: T


class City(BaseModel):
    name: Annotated[str, Field(description="City name")]
    city_code: Annotated[str, Field(description="Metropolitan area IATA code")]


def get_city_code(city_name: str) -> ApiResponse[City]:
    """
    Get city code from city name.
    """
    return ApiResponse[City](response=City(city_code="NYC", name="New York City"))


@prompt_chain("Provide city code for {city_name}",
              functions=[get_city_code])
def provide_city_code(city_name: str) -> str:
    ...


if __name__ == '__main__':
    print(provide_city_code("foo"))

``` 

## Error

```
023-11-01 01:26:02,795 - openai - INFO - error_code=None error_message="'return_apiresponse[city]' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.2.name'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Traceback (most recent call last):
  File "/workspace/chat.py", line 169, in <module>
    print(provide_city_code("foo"))
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/magentic/prompt_chain.py", line 83, in wrapper
    chat = chat.exec_function_call().submit()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/magentic/chat.py", line 81, in submit
    output_message: AssistantMessage[Any] = self._model.complete(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/magentic/chat_model/openai_chat_model.py", line 282, in complete
    response = openai_chatcompletion_create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/magentic/chat_model/openai_chat_model.py", line 144, in openai_chatcompletion_create
    response: Iterator[dict[str, Any]] = openai.ChatCompletion.create(  # type: ignore[no-untyped-call]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/workspace/.local/share/virtualenvs/ZP357Yhn/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'return_apiresponse[city]' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.2.name'


```

**Comment by thomasleveil** [comment]
I'm not sure if the fix is to be made in magentic of upstream in openai.

**Comment by jackmpcollins** [comment]
@thomasleveil Fixed now in PR https://github.com/jackmpcollins/magentic/pull/52 and released in https://github.com/jackmpcollins/magentic/releases/tag/v0.8.0 Thanks for reporting this and providing the reproducible example!
