### ISSUE TITLE
ollama example does not run

### ISSUE THREAD

**Issue by altruios** [jackmpcollins/magentic#78]
Running this code
```py
#main.py
from magentic import prompt, StreamedStr
@prompt("Say hello as a {text}")
def say_hello(text) -> StreamedStr:
    ...
for chunk in say_hello("cat"):
    print(chunk, end="")


```
...with this change
```
#../magentic/settings.py
    backend: Backend = Backend.LITELLM
    litellm_model: str = "ollama/mixtral:latest"
    #llama2 does not work, no models I have seem to work.

```
...and having a working ollama server loaded with the model...

I try running the code. 

I get the following error:

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5828, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5651, in handle_ollama_stream
    raise e
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5632, in handle_ollama_stream
    json_chunk = json.loads(chunk)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "{dir}/main.py", line 5, in <module>
    for chunk in say_hello("cat"):
                 ^^^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/magentic/prompt_function.py", line 79, in __call__
    message = self.model.complete(
              ^^^^^^^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/magentic/chat_model/litellm_chat_model.py", line 215, in complete
    first_chunk = next(response)
                  ^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5946, in __next__
    raise e
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5932, in __next__
    response = self.chunk_creator(chunk=chunk)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5919, in chunk_creator
    raise exception_type(model=self.model, custom_llm_provider=self.custom_llm_provider, original_exception=e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5192, in exception_type
    raise e
  File "{dir}/lib/python3.11/site-packages/litellm/utils.py", line 5169, in exception_type
    raise APIConnectionError( 
    ^^^^^^^^^^^^^^^^^^^^^^^^^
litellm.exceptions.APIConnectionError: the JSON object must be str, bytes or bytearray, not dict

```

Which seems to be from litellm.

Digging further I found the culprit to be an object/dict shaped like:
```
{'role': 'assistant', 'content': '/n'}

```
...looks like it wants this shape:
```
{str:response,bool:done}
```
...instead.

That obj/dict is getting passed as the 'chunk' of this code in litellm's repo (chunk should be a string or such, but is an object/dict in this case, thus the error)
```
    def handle_ollama_stream(self, chunk): 
        try: 
            json_chunk = json.loads(chunk)
            if "error" in json_chunk: 
                raise Exception(f"Ollama Error - {json_chunk}")
            
            text = "" 
            is_finished = False
            finish_reason = None
            if json_chunk["done"] == True:
                text = ""
                is_finished = True
                finish_reason = "stop"
                return {"text": text, "is_finished": is_finished, "finish_reason": finish_reason}
            elif json_chunk["response"]:
                print_verbose(f"delta content: {json_chunk}")
                text = json_chunk["response"]
                return {"text": text, "is_finished": is_finished, "finish_reason": finish_reason}
            else: 
                raise Exception(f"Ollama Error - {json_chunk}")
        except Exception as e: 
            raise e
```

I'm not sure exactly what's going wrong, or if anything is wrong in this repo - but having installed and tested litellm alone and got it working in 20 seconds - I suspect the issue is not in that repo...

so (I haven't checked, and I'm tired!) I suspect some initial data is getting passed incorrectly to litellm... but that's just my (uneducated) guess.

**Comment by altruios** [comment]
sorry, more testing makes this seem like a litellm issue after all (I tested the full text response, not the stream response)...

**Comment by jackmpcollins** [comment]
Hi @altruios  Did you manage to solve this? The following code works for me with magentic v0.13.0 and litellm v1.0.0.

```python
from magentic import prompt, StreamedStr
from magentic.chat_model.litellm_chat_model import LitellmChatModel


@prompt(
    "Say hello as a {text}",
    model=LitellmChatModel("ollama/llama2"),
)
def say_hello(text) -> StreamedStr:
    ...


for chunk in say_hello("cat"):
    print(chunk, end="")
```
